#!/usr/bin/env ansible-playbook
---
# Deploy Velociraptor
- name: Deploy Velociraptor
  hosts: orochi_servers
  become: true
  gather_facts: true
  vars_files:
    - ../vars/secrets.yml
  
  roles:
    - common
    - velociraptor